### ISSUE TITLE
[bug] Lending app now breaks bank reconciliation

### ISSUE THREAD

**Issue by this-gavagai** [frappe/lending#173]
### Information about bug

Due to an unannounced API change in ERPNext 15.17, the hook method `lending.loan_management.utils.get_matching_queries` now causes the Bank Reconciliation tool to break on all sites using the Lending app.

Fixing this issue will require updating the method to use the new parameter requirements.
https://github.com/frappe/erpnext/issues/40493

### Module

Loan Management

### Version

ERPNext 15.17

### Installation method

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ruthra-kumar** [comment]
Fix: https://github.com/frappe/lending/pull/174
